### ISSUE TITLE
Some questions about Fig. 4 in paper

### ISSUE THREAD

**Issue by maxin-cn** [HolmesShuan/Zero-shot-Style-Transfer-via-Attention-Rearrangement#5]
Thank you for open-sourcing the code for this work. I have some questions regarding Figure 4 in the paper. Could you provide more details on what is meant by the "two content features" in this context? Thanks~

![image](https://github.com/user-attachments/assets/dfb581aa-f007-4ed9-8f71-59c509eac288)

**Comment by HolmesShuan** [comment]
Thank you for your interest, and I apologize for any confusion caused by the initial description. Here are additional details for clarification:
- "Two": This refers to the feature maps both before and after applying Softmax, corresponding to the term “two.”
- "Content Feature": We use the term “content feature” for  $q_c K_s$ , as it will be used in subsequent steps for stylized content generation.
- "Points": Since we visualize the distribution of all points within the feature map, where the number of points is  $C \times H \times W$, we use the term “points” to describe this distribution.

**Comment by maxin-cn** [comment]
Thanks~
